### ISSUE TITLE
how to contribute for terra2 validator?

### ISSUE THREAD

**Issue by nampdn** [terra-money/genesis-tools#11]
Hi,
I'm eager to support Terra 2.0, as it's the community network now. Is it still able to include my validator to genesis validators list?

I'm following the https://docs.terra.money/docs/migration/validator-gentx.html#supplemental-resources but not sure if I'm required to sync and export snapshot?

And where I can submit my validator address?

**Comment by hanjukim** [comment]
Please look at: https://github.com/terra-money/genesis-tools/blob/main/LAUNCH.md

**Comment by nampdn** [comment]
Hi @hanjukim, according to the LAUNCH, when (a little bit late now) and where you will release the `preultimate-genesis.json` so I can keep track at?

**Comment by awsdataarchitect** [comment]
Yes but too late.  The address had to be in genesis-validators pre genesis phase.
